In [19]:
import pandas as pd
import numpy as np
from keras.preprocessing.image import ImageDataGenerator, DirectoryIterator
from skimage.feature import hog
import cv2

In [20]:
class ImageWithNames(DirectoryIterator):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.filenames_np = np.array(self.filepaths)

    def _get_batches_of_transformed_samples(self, index_array):
        return (super()._get_batches_of_transformed_samples(index_array),
                self.filenames_np[index_array])

In [21]:
train_datagen = ImageDataGenerator()
train_generator = ImageWithNames("F:/FYP/Data/PFDIC-20 O",
                         train_datagen,
                         target_size=(128,128),
                         color_mode='rgb',
                         batch_size=100,
                         class_mode='categorical',
                         shuffle=False)

Found 7426 images belonging to 20 classes.

In [22]:
HOG_X={}
HOG_Y={}
imgName={}
count1=0
count2=0
count3=0

for j in range(len(train_generator)):
    xy,file=train_generator[j]
    x,y=xy
    
    for c1 in x:
        
        #temp=hog(cv2.cvtColor(c1,cv2.COLOR_BGR2GRAY).astype("double"))
        temp=hog(c1, orientations=8, pixels_per_cell=(16,16),cells_per_block=(1, 1), multichannel=True)

        HOG_X[count1]=temp.flatten()
        count1+=1
        
    for c2 in y:
        HOG_Y[count2]=c2
        count2+=1
        
    for c3 in file:
        imgName[count3]=c3
        count3+=1

###### Y - Label

In [23]:
df2=pd.DataFrame(HOG_Y,columns=None).T

In [24]:
df2

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7421,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
7422,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
7423,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
7424,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
7425,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [25]:
s2 = pd.DataFrame(df2.idxmax(axis=1),columns=["Label"])

In [26]:
s2

      Label
0         0
1         0
2         0
3         0
4         0
...     ...
7421     19
7422     19
7423     19
7424     19
7425     19

[7426 rows x 1 columns]

###### FileNames

In [27]:
df3=pd.DataFrame(pd.Series(imgName,index=imgName.keys()),columns=["ID"])

In [28]:
df3

                                                 ID
0           F:/FYP/Data/PFDIC-20 O\Biryani\1001.jpg
1           F:/FYP/Data/PFDIC-20 O\Biryani\1002.jpg
2           F:/FYP/Data/PFDIC-20 O\Biryani\1003.jpg
3           F:/FYP/Data/PFDIC-20 O\Biryani\1004.jpg
4           F:/FYP/Data/PFDIC-20 O\Biryani\1005.jpg
...                                             ...
7421  F:/FYP/Data/PFDIC-20 O\Shahi Tukray\20269.jpg
7422  F:/FYP/Data/PFDIC-20 O\Shahi Tukray\20273.jpg
7423  F:/FYP/Data/PFDIC-20 O\Shahi Tukray\20275.jpg
7424  F:/FYP/Data/PFDIC-20 O\Shahi Tukray\20276.jpg
7425  F:/FYP/Data/PFDIC-20 O\Shahi Tukray\20277.jpg

[7426 rows x 1 columns]

In [29]:
###### X - Features

In [30]:
df=pd.DataFrame(HOG_X,columns=None).T

In [31]:
df

,0,1,2,3,4,5,6,7,8,9,...,502,503,504,505,506,507,508,509,510,511
0,0.770951,0.439091,0.304061,0.073550,0.116651,0.027283,0.027114,0.316044,0.444052,0.238725,...,0.050495,0.030197,0.398862,0.200401,0.477357,0.477357,0.462064,0.007011,0.089027,0.351469
1,0.408747,0.151581,0.261492,0.408747,0.408747,0.270692,0.408747,0.408747,0.141108,0.009015,...,0.124844,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.654903,0.654903,0.213924,0.012295,0.211077,0.057488,0.154164,0.157050,0.493796,0.401628,...,0.420965,0.420965,0.874848,0.247253,0.019288,0.000000,0.007529,0.008197,0.039741,0.414044
3,0.374422,0.374422,0.374422,0.374422,0.374422,0.367606,0.374422,0.153992,0.226315,0.354314,...,0.356854,0.329523,0.353553,0.353553,0.353553,0.353553,0.353553,0.353553,0.353553,0.353553
4,0.051746,0.011680,0.078929,0.702499,0.702499,0.060714,0.015433,0.004803,0.053325,0.025531,...,0.282670,0.134070,0.420176,0.172011,0.275051,0.109633,0.420176,0.420176,0.420176,0.420176
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7421,0.435715,0.435715,0.435715,0.435715,0.435715,0.074396,0.133917,0.165203,0.364704,0.304575,...,0.248735,0.192902,0.353553,0.353553,0.353553,0.353553,0.353553,0.353553,0.353553,0.353553
7422,0.357831,0.357831,0.357831,0.322021,0.357831,0.357831,0.357831,0.357831,0.354082,0.354082,...,0.081162,0.207030,0.492338,0.492338,0.492338,0.288377,0.355695,0.119603,0.208127,0.074221
7423,0.373957,0.291107,0.373957,0.373957,0.373957,0.276028,0.373957,0.373957,0.415417,0.428873,...,0.209759,0.374432,0.366278,0.366278,0.366278,0.246747,0.366278,0.366278,0.366278,0.366278
7424,0.483197,0.599031,0.599031,0.088238,0.197756,0.008945,0.024134,0.035884,0.368683,0.368683,...,0.297246,0.321428,0.359909,0.359909,0.359909,0.359909,0.359909,0.305385,0.359909,0.359909
7425,0.395303,0.395303,0.395303,0.395303,0.395303,0.094837,0.231121,0.395303,0.366630,0.366630,...,0.385173,0.385173,0.489135,0.170106,0.059999,0.077318,0.173368,0.462245,0.489135,0.489135

###### Data - FileName, X, Y

In [32]:
data=pd.concat([df3,df,s2], axis=1, sort=False)

In [33]:
data

,ID,0,1,2,3,4,5,6,7,8,...,503,504,505,506,507,508,509,510,511,Label
0,F:/FYP/Data/PFDIC-20 O\Biryani\1001.jpg,0.770951,0.439091,0.304061,0.073550,0.116651,0.027283,0.027114,0.316044,0.444052,...,0.030197,0.398862,0.200401,0.477357,0.477357,0.462064,0.007011,0.089027,0.351469,0
1,F:/FYP/Data/PFDIC-20 O\Biryani\1002.jpg,0.408747,0.151581,0.261492,0.408747,0.408747,0.270692,0.408747,0.408747,0.141108,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
2,F:/FYP/Data/PFDIC-20 O\Biryani\1003.jpg,0.654903,0.654903,0.213924,0.012295,0.211077,0.057488,0.154164,0.157050,0.493796,...,0.420965,0.874848,0.247253,0.019288,0.000000,0.007529,0.008197,0.039741,0.414044,0
3,F:/FYP/Data/PFDIC-20 O\Biryani\1004.jpg,0.374422,0.374422,0.374422,0.374422,0.374422,0.367606,0.374422,0.153992,0.226315,...,0.329523,0.353553,0.353553,0.353553,0.353553,0.353553,0.353553,0.353553,0.353553,0
4,F:/FYP/Data/PFDIC-20 O\Biryani\1005.jpg,0.051746,0.011680,0.078929,0.702499,0.702499,0.060714,0.015433,0.004803,0.053325,...,0.134070,0.420176,0.172011,0.275051,0.109633,0.420176,0.420176,0.420176,0.420176,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7421,F:/FYP/Data/PFDIC-20 O\Shahi Tukray\20269.jpg,0.435715,0.435715,0.435715,0.435715,0.435715,0.074396,0.133917,0.165203,0.364704,...,0.192902,0.353553,0.353553,0.353553,0.353553,0.353553,0.353553,0.353553,0.353553,19
7422,F:/FYP/Data/PFDIC-20 O\Shahi Tukray\20273.jpg,0.357831,0.357831,0.357831,0.322021,0.357831,0.357831,0.357831,0.357831,0.354082,...,0.207030,0.492338,0.492338,0.492338,0.288377,0.355695,0.119603,0.208127,0.074221,19
7423,F:/FYP/Data/PFDIC-20 O\Shahi Tukray\20275.jpg,0.373957,0.291107,0.373957,0.373957,0.373957,0.276028,0.373957,0.373957,0.415417,...,0.374432,0.366278,0.366278,0.366278,0.246747,0.366278,0.366278,0.366278,0.366278,19
7424,F:/FYP/Data/PFDIC-20 O\Shahi Tukray\20276.jpg,0.483197,0.599031,0.599031,0.088238,0.197756,0.008945,0.024134,0.035884,0.368683,...,0.321428,0.359909,0.359909,0.359909,0.359909,0.359909,0.305385,0.359909,0.359909,19
7425,F:/FYP/Data/PFDIC-20 O\Shahi Tukray\20277.jpg,0.395303,0.395303,0.395303,0.395303,0.395303,0.094837,0.231121,0.395303,0.366630,...,0.385173,0.489135,0.170106,0.059999,0.077318,0.173368,0.462245,0.489135,0.489135,19

In [16]:
data.to_csv("FAST.csv")